/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainWindow.java
 *
 * Created on 01.09.2011, 17:21:16
 */
package main.java.de.WegFetZ.AudioClient.gui;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Michael
 */
public class mainWindow extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form mainWindow */
    public mainWindow() {
    	initComponents();
        initOwnComponents();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("deprecation")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        tab_general = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_ip = new javax.swing.JTextField();
        tf_cmPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        check_debug = new javax.swing.JCheckBox();
        check_reconnect = new javax.swing.JCheckBox();
        scroll_sysOut = new javax.swing.JScrollPane();
        ta_sysOut = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        b_save = new javax.swing.JButton();
        b_connect = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        check_saveOnQuit = new javax.swing.JCheckBox();
        check_startCon = new javax.swing.JCheckBox();
        progress_download = new javax.swing.JProgressBar();
        progress_upload = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        l_uploadFile = new javax.swing.JLabel();
        l_downloadFile = new javax.swing.JLabel();
        l_uploadSpeed = new javax.swing.JLabel();
        l_downloadSpeed = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        tab_music = new javax.swing.JPanel();
        b_syncMusic = new javax.swing.JButton();
        b_addMusic = new javax.swing.JButton();
        b_deleteMusic = new javax.swing.JButton();
        b_refreshMusicList = new javax.swing.JButton();
        scroll_shoutcast1 = new javax.swing.JScrollPane();
        list_music = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        l_midiCount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l_size = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l_mp3Count = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_fileCount = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_upConSpeed = new javax.swing.JTextField();
        combo_connection = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        l_estTime = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        tab_webradio = new javax.swing.JPanel();
        scroll_shoutcast2 = new javax.swing.JScrollPane();
        list_shoutcastRadio = new javax.swing.JList();
        b_downloadStream = new javax.swing.JButton();
        b_refreshStreamList = new javax.swing.JButton();
        b_syncRadio = new javax.swing.JButton();
        scroll_ownRadio = new javax.swing.JScrollPane();
        list_ownRadio = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        b_deleteRadio = new javax.swing.JButton();
        b_addRadio = new javax.swing.JButton();
        b_searchStream = new javax.swing.JButton();
        tf_searchShoutcast = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        b_playOwnRadio = new javax.swing.JButton();
        tab_help = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        tab_info = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CustomMusic AudioClient");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabbedPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabbedPanel.setPreferredSize(new java.awt.Dimension(760, 439));
        tabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPanelStateChanged(evt);
            }
        });

        tab_general.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tab_general.setPreferredSize(new java.awt.Dimension(730, 409));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel1.setText("Minecraft name:");
        jLabel1.setToolTipText("Your Minecraft login name (case insensitive)");

        tf_name.setFont(new java.awt.Font("Arial", 0, 12));
        tf_name.setText("Herobrine");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel2.setText("Server-IP:");
        jLabel2.setToolTipText("The IP-address of the Minecraft server you want to connect to.");

        tf_ip.setFont(new java.awt.Font("Arial", 0, 12));
        tf_ip.setText("127.0.0.1");

        tf_cmPort.setFont(new java.awt.Font("Arial", 0, 12));
        tf_cmPort.setText("4224");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel3.setText("CustomMusic port: ");
        jLabel3.setToolTipText("The IP-address of the Minecraft server you want to connect to.");

        check_debug.setFont(new java.awt.Font("Arial", 0, 12));
        check_debug.setText("Debug mode");
        check_debug.setToolTipText("Run the audioclient in debug mode to show information on errors in the log.");
        check_debug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_debugActionPerformed(evt);
            }
        });

        check_reconnect.setFont(new java.awt.Font("Arial", 0, 12));
        check_reconnect.setText("Reconnect on disconnect");
        check_reconnect.setToolTipText("Reconnect to server when the player disconnects or loses connection. If the player doesn't initialize on the server within one minute, the connection will be closed.");

        scroll_sysOut.setAutoscrolls(true);

        ta_sysOut.setColumns(20);
        ta_sysOut.setEditable(false);
        ta_sysOut.setRows(5);
        scroll_sysOut.setViewportView(ta_sysOut);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        b_save.setFont(new java.awt.Font("Arial", 0, 12));
        b_save.setLabel("Save");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        b_connect.setFont(new java.awt.Font("Arial", 0, 12));
        b_connect.setText("Connect");
        b_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_connectActionPerformed(evt);
            }
        });

        check_saveOnQuit.setFont(new java.awt.Font("Arial", 0, 12));
        check_saveOnQuit.setText("Save on quit");
        check_saveOnQuit.setToolTipText("Save settings on quit.");

        check_startCon.setFont(new java.awt.Font("Arial", 0, 12));
        check_startCon.setText("Connect on startup.");
        check_startCon.setToolTipText("Connect to the server on program start.");
        check_startCon.setActionCommand("Connect on startup");

        progress_download.setStringPainted(true);

        progress_upload.setStringPainted(true);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel21.setText("Upload:");
        jLabel21.setToolTipText("Current upload progress");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel22.setText("Download:");
        jLabel22.setToolTipText("Current download progress");

        l_uploadFile.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l_uploadFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_uploadFile.setText("-");
        l_uploadFile.setToolTipText("Current file.");

        l_downloadFile.setFont(new java.awt.Font("Arial", 0, 11));
        l_downloadFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_downloadFile.setText("-");

        l_uploadSpeed.setFont(new java.awt.Font("Arial", 0, 12));
        l_uploadSpeed.setText("0 Kb/s");
        l_uploadSpeed.setToolTipText("Current upload rate.");

        l_downloadSpeed.setFont(new java.awt.Font("Arial", 0, 12));
        l_downloadSpeed.setText("0 Kb/s");
        l_downloadSpeed.setToolTipText("Current download rate.");

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout tab_generalLayout = new javax.swing.GroupLayout(tab_general);
        tab_general.setLayout(tab_generalLayout);
        tab_generalLayout.setHorizontalGroup(
            tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_generalLayout.createSequentialGroup()
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tab_generalLayout.createSequentialGroup()
                                .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(tab_generalLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tab_generalLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_cmPort))
                                        .addGroup(tab_generalLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1))
                                    .addComponent(check_debug)
                                    .addComponent(check_saveOnQuit)
                                    .addComponent(check_startCon)
                                    .addComponent(check_reconnect))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scroll_sysOut))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(tab_generalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(b_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_generalLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_uploadSpeed))
                            .addComponent(progress_upload, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(l_uploadFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_generalLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_downloadSpeed))
                            .addComponent(progress_download, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_downloadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        tab_generalLayout.setVerticalGroup(
            tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_generalLayout.createSequentialGroup()
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_cmPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_startCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_reconnect)
                        .addGap(18, 18, 18)
                        .addComponent(check_saveOnQuit)
                        .addGap(3, 3, 3)
                        .addComponent(check_debug))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scroll_sysOut, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_save, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_generalLayout.createSequentialGroup()
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(l_uploadSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(l_uploadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress_upload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_generalLayout.createSequentialGroup()
                        .addGroup(tab_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(l_downloadSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(l_downloadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress_download, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator23, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jSeparator20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(b_connect, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPanel.addTab("General", tab_general);

        b_syncMusic.setFont(new java.awt.Font("Arial", 0, 12));
        b_syncMusic.setText("Synchronize");
        b_syncMusic.setToolTipText("Synchronize your songs and webradio files with the server.");
        b_syncMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_syncMusicActionPerformed(evt);
            }
        });

        b_addMusic.setFont(new java.awt.Font("Arial", 0, 12));
        b_addMusic.setText("Add files...");
        b_addMusic.setToolTipText("Copy music files from your PC to your music list.");
        b_addMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addMusicActionPerformed(evt);
            }
        });

        b_deleteMusic.setFont(new java.awt.Font("Arial", 0, 12));
        b_deleteMusic.setText("Delete");
        b_deleteMusic.setToolTipText("Delete the selected file(s).");
        b_deleteMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteMusicActionPerformed(evt);
            }
        });

        b_refreshMusicList.setFont(new java.awt.Font("Arial", 0, 12));
        b_refreshMusicList.setText("Refresh");
        b_refreshMusicList.setToolTipText("Reload the list and statistics.");
        b_refreshMusicList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_refreshMusicListActionPerformed(evt);
            }
        });

        list_music.setFont(new java.awt.Font("Arial", 0, 12));
        scroll_shoutcast1.setViewportView(list_music);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel6.setText("- midi:");
        jLabel6.setToolTipText("Number of midi files.");

        l_midiCount.setFont(new java.awt.Font("Arial", 0, 12));
        l_midiCount.setText("-");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel7.setText("Total size:");
        jLabel7.setToolTipText("Total size of selected files.");

        l_size.setFont(new java.awt.Font("Arial", 0, 12));
        l_size.setText("-");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel5.setText("- mp3:");
        jLabel5.setToolTipText("Number of mp3 files.");

        l_mp3Count.setFont(new java.awt.Font("Arial", 0, 12));
        l_mp3Count.setText("-");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("Files:");

        l_fileCount.setFont(new java.awt.Font("Arial", 1, 14));
        l_fileCount.setText("-");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel10.setText("Connection:");
        jLabel10.setToolTipText("Your internet connection type.");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel24.setText("Upload rate:");
        jLabel24.setToolTipText("Upload rate for your connection.");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel23.setText("Kb/s");

        tf_upConSpeed.setEditable(false);
        tf_upConSpeed.setFont(new java.awt.Font("Arial", 0, 12));
        tf_upConSpeed.setText("80");
        tf_upConSpeed.setToolTipText("Upload rate for your chosen connection.");
        tf_upConSpeed.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_upConSpeedCaretUpdate(evt);
            }
        });

        combo_connection.setFont(new java.awt.Font("Arial", 0, 12));
        combo_connection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DSL 384", "DSL 1000", "DSL 2000", "DSL 3000", "DSL 6000", "DSL 16000", "VDSL 25", "VDSL 50", "Use own:" }));
        combo_connection.setSelectedIndex(4);
        combo_connection.setToolTipText("Your internet connection. Select use upload rate to claculate with your own value.");
        combo_connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_connectionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel8.setText("Estimated upload time:");
        jLabel8.setToolTipText("Estimated time that is needed to upload the selected files with the selected internet connection.");

        l_estTime.setFont(new java.awt.Font("Arial", 0, 12));
        l_estTime.setText("00h:00m:00s");

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout tab_musicLayout = new javax.swing.GroupLayout(tab_music);
        tab_music.setLayout(tab_musicLayout);
        tab_musicLayout.setHorizontalGroup(
            tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_musicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_syncMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tab_musicLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(l_fileCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(tab_musicLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(l_size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(tab_musicLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(l_midiCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(tab_musicLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(l_mp3Count, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tab_musicLayout.createSequentialGroup()
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addGroup(tab_musicLayout.createSequentialGroup()
                                .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addGroup(tab_musicLayout.createSequentialGroup()
                                        .addComponent(tf_upConSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23))))
                            .addComponent(jLabel8)
                            .addGroup(tab_musicLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(l_estTime, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_musicLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(b_addMusic)
                        .addGap(18, 18, 18)
                        .addComponent(b_deleteMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(b_refreshMusicList)
                        .addGap(31, 31, 31))
                    .addGroup(tab_musicLayout.createSequentialGroup()
                        .addComponent(scroll_shoutcast1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        tab_musicLayout.setVerticalGroup(
            tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_musicLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_musicLayout.createSequentialGroup()
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_fileCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_mp3Count, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_midiCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_connection)
                            .addComponent(tf_upConSpeed)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_estTime)
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_syncMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_musicLayout.createSequentialGroup()
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scroll_shoutcast1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_musicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_refreshMusicList)
                            .addComponent(b_addMusic)
                            .addComponent(b_deleteMusic))))
                .addContainerGap())
        );

        tabbedPanel.addTab("Music", tab_music);

        list_shoutcastRadio.setFont(new java.awt.Font("Arial", 0, 12));
        scroll_shoutcast2.setViewportView(list_shoutcastRadio);

        b_downloadStream.setFont(new java.awt.Font("Arial", 0, 12));
        b_downloadStream.setText("Download");
        b_downloadStream.setToolTipText("Downloads a .pls file for the selected stream to be uploaded to the server.");
        b_downloadStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_downloadStreamActionPerformed(evt);
            }
        });

        b_refreshStreamList.setFont(new java.awt.Font("Arial", 0, 12));
        b_refreshStreamList.setText("Top 100");
        b_refreshStreamList.setToolTipText("Reload the list from shoutcast.com.");
        b_refreshStreamList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_refreshStreamListActionPerformed(evt);
            }
        });

        b_syncRadio.setFont(new java.awt.Font("Arial", 0, 12));
        b_syncRadio.setText("Synchronize");
        b_syncRadio.setToolTipText("Synchronize your songs and webradio files with the server.");
        b_syncRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_syncRadioActionPerformed(evt);
            }
        });

        scroll_ownRadio.setFont(new java.awt.Font("Arial", 0, 10));

        list_ownRadio.setFont(new java.awt.Font("Arial", 0, 11));
        scroll_ownRadio.setViewportView(list_ownRadio);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel12.setText("Your stations:");

        b_deleteRadio.setFont(new java.awt.Font("Arial", 0, 11));
        b_deleteRadio.setText("Delete");
        b_deleteRadio.setToolTipText("Delete the selected files.");
        b_deleteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteRadioActionPerformed(evt);
            }
        });

        b_addRadio.setFont(new java.awt.Font("Arial", 0, 11));
        b_addRadio.setText("Add");
        b_addRadio.setToolTipText("Add a stream file from your PC to the list.");
        b_addRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addRadioActionPerformed(evt);
            }
        });

        b_searchStream.setFont(new java.awt.Font("Arial", 0, 12));
        b_searchStream.setText("Search");
        b_searchStream.setToolTipText("Search for a stream on shoutcast.com");
        b_searchStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_searchStreamActionPerformed(evt);
            }
        });

        tf_searchShoutcast.setFont(new java.awt.Font("Arial", 0, 12));
        tf_searchShoutcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_searchShoutcastActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel9.setText("SHOUTcastâ„¢ Stations");

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        b_playOwnRadio.setFont(new java.awt.Font("Arial", 0, 11));
        b_playOwnRadio.setText("Play");
        b_playOwnRadio.setToolTipText("Play/ stop the selected stream (or the first selected stream if you selected several ones).");
        b_playOwnRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_playOwnRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_webradioLayout = new javax.swing.GroupLayout(tab_webradio);
        tab_webradio.setLayout(tab_webradioLayout);
        tab_webradioLayout.setHorizontalGroup(
            tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_webradioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b_syncRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addGroup(tab_webradioLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(b_playOwnRadio)
                            .addGap(18, 18, 18)
                            .addComponent(b_deleteRadio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_addRadio))
                        .addComponent(scroll_ownRadio, 0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(tab_webradioLayout.createSequentialGroup()
                        .addComponent(tf_searchShoutcast, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_searchStream)))
                .addGap(36, 36, 36)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_webradioLayout.createSequentialGroup()
                        .addComponent(scroll_shoutcast2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(tab_webradioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(b_downloadStream)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(b_refreshStreamList)
                        .addGap(31, 31, 31))))
        );
        tab_webradioLayout.setVerticalGroup(
            tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_webradioLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_webradioLayout.createSequentialGroup()
                        .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_searchShoutcast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_searchStream))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scroll_ownRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_addRadio)
                            .addComponent(b_deleteRadio)
                            .addComponent(b_playOwnRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(b_syncRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_webradioLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scroll_shoutcast2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_webradioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_downloadStream)
                            .addComponent(b_refreshStreamList))))
                .addContainerGap())
            .addGroup(tab_webradioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Webradio", tab_webradio);

        tab_help.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel25.setText("Ingame commands:");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel26.setText("/cm init");
        jLabel26.setToolTipText("initialize the AudioClient, in case you connected to the server after you logged into Minecraft");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel27.setText("/cm help [page]");
        jLabel27.setToolTipText("Show a list of all commands.");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel28.setText("/cm toggle");
        jLabel28.setToolTipText("Toggle the music.");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel29.setText("/cm volume <value>");
        jLabel29.setToolTipText("Change the volume of the music.");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel30.setText("/cm status");
        jLabel30.setToolTipText("Check if you are in range of any box or area.");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel31.setText("/cm users");
        jLabel31.setToolTipText("Get a list of players that are currently using the audioclient.");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel32.setText("'<  >' means that the parameter is required, whereas '[  ]' means that the parameter is optional.");
        jLabel32.setToolTipText("");

        jLabel33.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel33.setText("General commands");
        jLabel33.setToolTipText("");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel34.setText("Hold the mouse over a command until the Tooltip pops up to get more information on the command.");
        jLabel34.setToolTipText("Yay, exactly like this ;)");

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel35.setText("Playing commands");
        jLabel35.setToolTipText("");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel36.setText("/cm play [player] <songnumbers>");
        jLabel36.setToolTipText("Play a song only for you. If you use the player parameter you can play songs from other players. Songnumbers must be seperated by comma. You can use 'all' to play every song. ");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel37.setText("/cm gplay [player] <songnumbers>");
        jLabel37.setToolTipText("Play a song globally for everybody. If you use the player parameter you can play songs from other players. Songnumbers must be seperated by comma. You can use 'all' to play every song. ");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel38.setText("/cm playradio [player] <radionumber>");
        jLabel38.setToolTipText("Play a webradio station only for you. If you use the player parameter you can play radio stations from other players.");

        jLabel39.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel39.setText("/cm gplayradio [player] <radionumber>");
        jLabel39.setToolTipText("Play a webradio station globally everyboy. If you use the player parameter you can play radio stations from other players.");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel40.setText("/cm stop");
        jLabel40.setToolTipText("Stop the song or radiostation you are currently playing with '/cm play',");

        jLabel41.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel41.setText("/cm gstop");
        jLabel41.setToolTipText("Stop the song or radiostation you are currently playing with '/cm gplay',");

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel42.setText("Box commands");
        jLabel42.setToolTipText("");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel43.setText("/cm setbox <number> [range] [priority]");
        jLabel43.setToolTipText("Set a box at your current location. Range is the distance from where the box can be heard.  Priority is used to manage the volume of overlapping boxes/ areas.");

        jLabel44.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel44.setText("/cm deletebox [player] <number>");
        jLabel44.setToolTipText("Delete a box [from another player].");

        jLabel45.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel45.setText("/cm bchoose <number> <songnumbers>");
        jLabel45.setToolTipText("Choose the songs a box shall play. Songnumbers must be seperated by comma. You can use 'all' to choose all your songs.");

        jLabel46.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel46.setText("/cm bchooseradio <number> <radionumber>");
        jLabel46.setToolTipText("Choose the webradio station a box shall play.");

        jLabel47.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel47.setText("/cm boxlist [player] <page>");
        jLabel47.setToolTipText("List all boxes [of a player].");

        jLabel48.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel48.setText("Area commands");
        jLabel48.setToolTipText("");

        jLabel49.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel49.setText("/cm arealist [player] <page>");
        jLabel49.setToolTipText("List all areas [of a player].");

        jLabel50.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel50.setText("/cm achooseradio <number> <radionumber>");
        jLabel50.setToolTipText("Choose the webradio station an area shall play.");

        jLabel51.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel51.setText("/cm achoose <number> <songnumbers>");
        jLabel51.setToolTipText("Choose the songs an area shall play. Songnumbers must be seperated by comma. You can use 'all' to choose all your songs.");

        jLabel52.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel52.setText("/cm deletearea [player] <number>");
        jLabel52.setToolTipText("Delete an area [from another player].");

        jLabel53.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel53.setText("/cm setarea <number> [f-range] [priority]");
        jLabel53.setToolTipText("Set a previously defined area. F-Range is the distance to the wall of an area at which the music will begin to fade in/out. Priority is used to manage the volume of overlapping boxes/ areas.");

        jLabel54.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel54.setText("/cm definearea <1|2>");
        jLabel54.setToolTipText("Define the corners of a cuboid area. Use either '1' or '2' as parameter.");

        jLabel55.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel55.setText("Ignore commands");
        jLabel55.setToolTipText("");

        jLabel56.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel56.setText("/cm ignorebox <player> <number>");
        jLabel56.setToolTipText("Ignore a box of a player.");

        jLabel57.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel57.setText("/cm ignorearea <player> <number>");
        jLabel57.setToolTipText("Ignore an area of a player.");

        jLabel58.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel58.setText("/cm unignorebox <player> <number>");
        jLabel58.setToolTipText("Stop ignoring a box of a player.");

        jLabel59.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel59.setText("/cm unignorearea <player> <number>");
        jLabel59.setToolTipText("Stop ignoring an area of a player.");

        jLabel60.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel60.setText("/cm ignorelist <page>");
        jLabel60.setToolTipText("Get a list of ignored boxes and areas.");

        jLabel61.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel61.setText("/cm songlist [player] <page>");
        jLabel61.setToolTipText("List songs [of a player].");

        jLabel62.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel62.setText("/cm radiolist [player] <page>");
        jLabel62.setToolTipText("List webradio stations [of a player]. ");

        jLabel63.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel63.setText("/cm deletesong [player] <number>");
        jLabel63.setToolTipText("Delete a song [of a player].");

        jLabel64.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel64.setText("/cm deleteradio [player] <number>");
        jLabel64.setToolTipText("Delete a webradio station [of a player].");

        javax.swing.GroupLayout tab_helpLayout = new javax.swing.GroupLayout(tab_help);
        tab_help.setLayout(tab_helpLayout);
        tab_helpLayout.setHorizontalGroup(
            tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_helpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_helpLayout.createSequentialGroup()
                        .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(tab_helpLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel64))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addGroup(tab_helpLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel36)))
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)
                            .addGroup(tab_helpLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel60))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_helpLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel54)
                                .addGap(131, 131, 131))
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_helpLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel47)))
                            .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel52)
                                .addComponent(jLabel53)
                                .addComponent(jLabel51)
                                .addComponent(jLabel50)
                                .addComponent(jLabel49))
                            .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel25)
                    .addComponent(jLabel34)
                    .addComponent(jLabel32))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        tab_helpLayout.setVerticalGroup(
            tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_helpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(tab_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(tab_helpLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel64))
                    .addGroup(tab_helpLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel60))
                    .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(tab_helpLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49)))
                .addContainerGap())
        );

        tabbedPanel.addTab("Help", tab_help);

        tab_info.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel13.setFont(new java.awt.Font("Narkisim", 3, 48));
        jLabel13.setText("CustomMusic: AudioClient");

        jLabel14.setFont(new java.awt.Font("Narkisim", 3, 36));
        jLabel14.setText("2011 by");

        jLabel15.setFont(new java.awt.Font("Narkisim", 3, 48));
        jLabel15.setText("WegFetZ");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel16.setText("Issues?");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18));
        jTextField1.setForeground(new java.awt.Color(0, 0, 255));
        jTextField1.setText("http://forums.bukkit.org/threads/9022");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel17.setText("Visit");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("To use the audioclient with your server, you need the CustomMusic plugin which can be found at the link posted above.");
        jLabel18.setAlignmentX(0.5F);
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel19.setText("Suggestions?");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel20.setText("Questions?");

        javax.swing.GroupLayout tab_infoLayout = new javax.swing.GroupLayout(tab_info);
        tab_info.setLayout(tab_infoLayout);
        tab_infoLayout.setHorizontalGroup(
            tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_infoLayout.createSequentialGroup()
                .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_infoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(tab_infoLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_infoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20)
                        .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_infoLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel16))
                            .addGroup(tab_infoLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel19))))
                    .addGroup(tab_infoLayout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(tab_infoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_infoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        tab_infoLayout.setVerticalGroup(
            tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_infoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab_infoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel20)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_infoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(54, 54, 54)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_infoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(37, 37, 37)))
                .addGroup(tab_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(67, 67, 67)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        tabbedPanel.addTab("Info", tab_info);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void initOwnComponents() {
    	
    	//music list
    	list_musicModel = new DefaultListModel();
    	list_music.setModel(list_musicModel);
        ListSelectionListener listSelectionListener = new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
            	list_musicSelected();
            }
          };
        list_music.addListSelectionListener(listSelectionListener);
        
        //own radio list
        list_ownRadioModel = new DefaultListModel();
    	list_ownRadio.setModel(list_ownRadioModel);
    	
    	//shoutcast radio list
    	list_shoutcastRadioModel = new DefaultListModel();
    	list_shoutcastRadio.setModel(list_shoutcastRadioModel);
    	
    	jLabel9.setText("SHOUTcast™ Stations");
    }
    
    
private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
	new guiAction("formClose").start();
}//GEN-LAST:event_formWindowClosing

private void tabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPanelStateChanged
    new guiAction("tabbedPanel").start();
}//GEN-LAST:event_tabbedPanelStateChanged

private void tf_upConSpeedCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_upConSpeedCaretUpdate
    new guiAction("tf_upConSpeed").start();
    
}//GEN-LAST:event_tf_upConSpeedCaretUpdate

private void list_musicSelected() {
	new guiAction("list_musicSelected").start();
}

private void combo_connectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_connectionActionPerformed
    new guiAction("combo_connection").start();
}//GEN-LAST:event_combo_connectionActionPerformed

private void b_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_connectActionPerformed
	new guiAction("b_connect").start();        
}//GEN-LAST:event_b_connectActionPerformed

private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
	new guiAction("b_save").start();
}//GEN-LAST:event_b_saveActionPerformed

private void check_debugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_debugActionPerformed
    new guiAction("check_debug").start();
}//GEN-LAST:event_check_debugActionPerformed

private void b_syncMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_syncMusicActionPerformed
    new guiAction("synchronize").start();
}//GEN-LAST:event_b_syncMusicActionPerformed

private void b_syncRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_syncRadioActionPerformed
    new guiAction("synchronize").start();
}//GEN-LAST:event_b_syncRadioActionPerformed

private void b_deleteMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteMusicActionPerformed
    new guiAction("b_deleteMusic").start();
}//GEN-LAST:event_b_deleteMusicActionPerformed

private void b_refreshMusicListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_refreshMusicListActionPerformed
    new guiAction("b_refreshMusicList").start();
}//GEN-LAST:event_b_refreshMusicListActionPerformed

private void b_addMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addMusicActionPerformed
    new guiAction("b_addMusic").start();
}//GEN-LAST:event_b_addMusicActionPerformed

private void b_addRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addRadioActionPerformed
    new guiAction("b_addRadio").start();
}//GEN-LAST:event_b_addRadioActionPerformed

private void b_deleteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteRadioActionPerformed
    new guiAction("b_deleteRadio").start();
}//GEN-LAST:event_b_deleteRadioActionPerformed

private void b_playOwnRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_playOwnRadioActionPerformed
    new guiAction("b_playOwnRadio").start();
}//GEN-LAST:event_b_playOwnRadioActionPerformed

private void b_refreshStreamListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_refreshStreamListActionPerformed
    new guiAction("b_refreshStreamList").start();
}//GEN-LAST:event_b_refreshStreamListActionPerformed

private void b_searchStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_searchStreamActionPerformed
    new guiAction("b_searchShoutcast").start();
}//GEN-LAST:event_b_searchStreamActionPerformed

private void tf_searchShoutcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_searchShoutcastActionPerformed
    new guiAction("b_searchShoutcast").start();
}//GEN-LAST:event_tf_searchShoutcastActionPerformed

private void b_downloadStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_downloadStreamActionPerformed
    new guiAction("b_downloadStream").start();
}//GEN-LAST:event_b_downloadStreamActionPerformed



    /*

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
    */ // not needed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton b_addMusic;
    public static javax.swing.JButton b_addRadio;
    public static javax.swing.JButton b_connect;
    public static javax.swing.JButton b_deleteMusic;
    public static javax.swing.JButton b_deleteRadio;
    public static javax.swing.JButton b_downloadStream;
    public static javax.swing.JButton b_playOwnRadio;
    public static javax.swing.JButton b_refreshMusicList;
    public static javax.swing.JButton b_refreshStreamList;
    public static javax.swing.JButton b_save;
    public static javax.swing.JButton b_searchStream;
    public static javax.swing.JButton b_syncMusic;
    public static javax.swing.JButton b_syncRadio;
    public static javax.swing.JCheckBox check_debug;
    public static javax.swing.JCheckBox check_reconnect;
    public static javax.swing.JCheckBox check_saveOnQuit;
    public static javax.swing.JCheckBox check_startCon;
    public static javax.swing.JComboBox combo_connection;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel27;
    public static javax.swing.JLabel jLabel28;
    public static javax.swing.JLabel jLabel29;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel30;
    public static javax.swing.JLabel jLabel31;
    public static javax.swing.JLabel jLabel32;
    public static javax.swing.JLabel jLabel33;
    public static javax.swing.JLabel jLabel34;
    public static javax.swing.JLabel jLabel35;
    public static javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabel37;
    public static javax.swing.JLabel jLabel38;
    public static javax.swing.JLabel jLabel39;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel40;
    public static javax.swing.JLabel jLabel41;
    public static javax.swing.JLabel jLabel42;
    public static javax.swing.JLabel jLabel43;
    public static javax.swing.JLabel jLabel44;
    public static javax.swing.JLabel jLabel45;
    public static javax.swing.JLabel jLabel46;
    public static javax.swing.JLabel jLabel47;
    public static javax.swing.JLabel jLabel48;
    public static javax.swing.JLabel jLabel49;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel50;
    public static javax.swing.JLabel jLabel51;
    public static javax.swing.JLabel jLabel52;
    public static javax.swing.JLabel jLabel53;
    public static javax.swing.JLabel jLabel54;
    public static javax.swing.JLabel jLabel55;
    public static javax.swing.JLabel jLabel56;
    public static javax.swing.JLabel jLabel57;
    public static javax.swing.JLabel jLabel58;
    public static javax.swing.JLabel jLabel59;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel60;
    public static javax.swing.JLabel jLabel61;
    public static javax.swing.JLabel jLabel62;
    public static javax.swing.JLabel jLabel63;
    public static javax.swing.JLabel jLabel64;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JSeparator jSeparator1;
    public static javax.swing.JSeparator jSeparator10;
    public static javax.swing.JSeparator jSeparator12;
    public static javax.swing.JSeparator jSeparator13;
    public static javax.swing.JSeparator jSeparator14;
    public static javax.swing.JSeparator jSeparator15;
    public static javax.swing.JSeparator jSeparator16;
    public static javax.swing.JSeparator jSeparator17;
    public static javax.swing.JSeparator jSeparator18;
    public static javax.swing.JSeparator jSeparator19;
    public static javax.swing.JSeparator jSeparator2;
    public static javax.swing.JSeparator jSeparator20;
    public static javax.swing.JSeparator jSeparator23;
    public static javax.swing.JSeparator jSeparator3;
    public static javax.swing.JSeparator jSeparator4;
    public static javax.swing.JSeparator jSeparator8;
    public static javax.swing.JSeparator jSeparator9;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel l_downloadFile;
    public static javax.swing.JLabel l_downloadSpeed;
    public static javax.swing.JLabel l_estTime;
    public static javax.swing.JLabel l_fileCount;
    public static javax.swing.JLabel l_midiCount;
    public static javax.swing.JLabel l_mp3Count;
    public static javax.swing.JLabel l_size;
    public static javax.swing.JLabel l_uploadFile;
    public static javax.swing.JLabel l_uploadSpeed;
    public static javax.swing.JList list_music;
    public static javax.swing.JList list_ownRadio;
    public static javax.swing.JList list_shoutcastRadio;
    public static javax.swing.JProgressBar progress_download;
    public static javax.swing.JProgressBar progress_upload;
    public static javax.swing.JScrollPane scroll_ownRadio;
    public static javax.swing.JScrollPane scroll_shoutcast1;
    public static javax.swing.JScrollPane scroll_shoutcast2;
    public static javax.swing.JScrollPane scroll_sysOut;
    public static javax.swing.JTextArea ta_sysOut;
    public static javax.swing.JPanel tab_general;
    public static javax.swing.JPanel tab_help;
    public static javax.swing.JPanel tab_info;
    public static javax.swing.JPanel tab_music;
    public static javax.swing.JPanel tab_webradio;
    public static javax.swing.JTabbedPane tabbedPanel;
    public static javax.swing.JTextField tf_cmPort;
    public static javax.swing.JTextField tf_ip;
    public static javax.swing.JTextField tf_name;
    public static javax.swing.JTextField tf_searchShoutcast;
    public static javax.swing.JTextField tf_upConSpeed;
    // End of variables declaration//GEN-END:variables
    
    //own variables
    public static DefaultListModel list_musicModel;
    public static DefaultListModel list_ownRadioModel;
    public static DefaultListModel list_shoutcastRadioModel;
}
